name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Set npm cache directory
      run: npm config set cache /path/to/your/npm/cache

    - name: Update npm
      run: npm install -g npm@latest

    - run: npm ci --verbose
    - run: npm run build --if-present
